### ISSUE TITLE
手机号码正则不对，目前还不支持19x xxxx xxxx

### ISSUE THREAD

**Issue by phoenixsky** [Taonce/MVVM-T#2]
/**
 * 验证字符串是否符合手机号规则
 */
fun String.isPhoneNum(): Boolean {
    val rule = "^((13[0-9])|(14[5,7,9])|(15[^4])|(18[0-9])|(17[0,1,3,5,6,7,8]))\\d{8}$"
    return (!this.isEmpty() && this.matches(Regex(rule)))
}

**Comment by Taonce** [comment]
ths，已更新规则
